---
title: "Quality Labels Collection Day 1"
output: html_notebook
---

Load seurat
```{r, message=F, warning=F}
library(Seurat)
```

```{r}
dir <- "./collections/e1"
```
## Collection Day 1

### Collection 1
```{r}
fname <- paste0(dir, "cd1col1")
sc <- readRDS(fname)
```

```{r}
DimPlot(sc, group.by="diffday")
FeaturePlot(sc, features=c("percent.mito"))
FeaturePlot(sc, features=c("demux.dbl.prb"))
FeaturePlot(sc, features=c("nCount_RNA"))
FeaturePlot(sc, features=c("nFeature_RNA"))
DimPlot(sc, group.by="seurat_clusters")
```

The ugly: 1 (doublets), 13 (mito)
```{r}
sc$ugly <- sc$seurat_clusters %in% c(1, 13)
DimPlot(sc, group.by="ugly")
```

### Collection 2
```{r}
fname <- paste0(dir, "cd1col2")
sc <- readRDS(fname)
```

```{r}
DimPlot(sc, group.by="diffday")
FeaturePlot(sc, features=c("percent.mito"))
FeaturePlot(sc, features=c("demux.dbl.prb"))
FeaturePlot(sc, features=c("nCount_RNA"))
FeaturePlot(sc, features=c("nFeature_RNA"))
DimPlot(sc, group.by="seurat_clusters")
```

The ugly: 3, 5 (doublets), 14 (mito)
```{r}
sc$ugly <- sc$seurat_clusters %in% c(3, 5, 14)
DimPlot(sc, group.by="ugly")
```

### Collection 3
```{r}
fname <- paste0(dir, "cd1col3")
sc <- readRDS(fname)
```

```{r}
DimPlot(sc, group.by="diffday")
FeaturePlot(sc, features=c("percent.mito"))
FeaturePlot(sc, features=c("demux.dbl.prb"))
FeaturePlot(sc, features=c("nCount_RNA"))
FeaturePlot(sc, features=c("nFeature_RNA"))
DimPlot(sc, group.by="seurat_clusters")
```

The ugly: 0 (both), 12 (mito), 9 (doublets)
```{r}
sc$ugly <- sc$seurat_clusters %in% c(0, 9, 12)
DimPlot(sc, group.by="ugly")
```

### Collection 4
```{r}
fname <- paste0(dir, "cd1col4")
sc <- readRDS(fname)
```

```{r}
DimPlot(sc, group.by="diffday")
FeaturePlot(sc, features=c("percent.mito"))
FeaturePlot(sc, features=c("demux.dbl.prb"))
FeaturePlot(sc, features=c("nCount_RNA"))
FeaturePlot(sc, features=c("nFeature_RNA"))
DimPlot(sc, group.by="seurat_clusters")
```

The ugly: 0 (both), 12 (mito)
```{r}
sc$ugly <- sc$seurat_clusters %in% c(0, 12)
DimPlot(sc, group.by="ugly")
```

### Collection 5
```{r}
fname <- paste0(dir, "cd1col5")
sc <- readRDS(fname)
```

```{r}
DimPlot(sc, group.by="diffday")
FeaturePlot(sc, features=c("percent.mito"))
FeaturePlot(sc, features=c("demux.dbl.prb"))
FeaturePlot(sc, features=c("nCount_RNA"))
FeaturePlot(sc, features=c("nFeature_RNA"))
DimPlot(sc, group.by="seurat_clusters")
```

The ugly: 0 (both)
```{r}
sc$ugly <- sc$seurat_clusters %in% c(0)
DimPlot(sc, group.by="ugly")
```

### Collection 6
```{r}
fname <- paste0(dir, "cd1col6")
sc <- readRDS(fname)
```

```{r}
DimPlot(sc, group.by="diffday")
FeaturePlot(sc, features=c("percent.mito"))
FeaturePlot(sc, features=c("demux.dbl.prb"))
FeaturePlot(sc, features=c("nCount_RNA"))
FeaturePlot(sc, features=c("nFeature_RNA"))
DimPlot(sc, group.by="seurat_clusters")
```

The ugly: 0, 2, 10, 11
```{r}
sc$ugly <- sc$seurat_clusters %in% c(0, 10, 11)
DimPlot(sc, group.by="ugly")
```

